---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ggfips

```{r, include = F}
# readxl::read_xlsx("data-raw/incompleteCounty.xlsx") %>% 
#   mutate(fips = as.character(fips)) %>%
#   mutate(fips = str_pad(fips, width = 5, side = "left", "0")) %>%
#   mutate(fips = as.factor(fips)) %>%
#   # slice(1:100) %>%
#   ggplot() +
#   coord_sf() +
#   aes(fips = fips) +
#   geom_sf_county()
# 
# ggplot2::layer_data(last_plot())

```


```{r, eval = T}
library(tidyverse)
library(ggfips)

us_census %>% 
ggplot() +
  coord_sf() +
  aes(fips = fips) +
  aes(fill = mean_work_travel) +
  geom_sf_county() +
  scale_fill_viridis_c(option = "magma")
```


# spotlighting

```{r, eval = T}
us_census %>% 
ggplot() +
  coord_sf() +
  aes(fips = fips) +
  aes(fill = mean_work_travel) +
  geom_sf_county(state = "Illinois") +
  scale_fill_viridis_c(option = "magma")

last_plot() +
  geom_sf_county(state = "Illinois",
                 county = c("Cook", "Champaign"),
                 color = "red", linewidth = 1)

# aesthetic mapping quick change
last_plot() +
  aes(fill = per_capita_income) + 
  scale_fill_viridis_c()
```





```{r, eval = T}
us_census %>% 
ggplot() +
  coord_sf() +
  aes(fips = fips) +
  aes(fill = mean_work_travel) +
  geom_sf_county(state = "Texas") +
  scale_fill_viridis_c(option = "magma")


us_census %>% 
ggplot() +
  coord_sf() +
  aes(fips = fips) +
  aes(fill = mean_work_travel) +
  geom_sf_county(state = "Iowa") +
  scale_fill_viridis_c(option = "magma")

us_census %>% 
ggplot() +
  coord_sf() +
  aes(fips = fips) +
  aes(fill = mean_work_travel) +
  geom_sf_county(state = "New York") +
  scale_fill_viridis_c(option = "magma") +
  geom_sf_county(state = "New York",
                 county = c("Orange", 
                            "Putnam", 
                            "Westchester"), aes(color = name),
                 color = "red", linewidth = 1)
```


 
